
CREATE TABLE `sys_oplog_info`  (
  `id` varchar(36) CHARACTER SET utf8mb4 NOT NULL COMMENT '主键唯一标识',
  `tenant_id` varchar(36) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '租户id',
  `service_id` varchar(32) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '服务ID',
  `client_id` varchar(36) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '客户端id: PC端, 微程序, APP等 ',
  `request_id` varchar(36) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT 'http 请求id',
  `title` varchar(255) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '日志标题: 用户管理, 菜单管理等',
  `type` varchar(30) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '日志类型: button, uri',
  `type_title` varchar(255) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '日志类型: 按钮, 链接',
  `remote_type` varchar(255) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '操作类型: SAVE,UPDATE,JUMP,REMOVE',
  `remote_title` varchar(255) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '操作类型: 新增, 修改, 删除, 查看',
  `remote_ip` varchar(255) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '操作IP地址',
  `remote_address` varchar(255) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '操作地址',
  `remote_status` varchar(30) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '操作状态: 成功, 失败, 异常',
  `user_agent` varchar(1000) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '用户代理',
  `request_uri` varchar(255) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '请求URI',
  `method` varchar(100) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '操作方式',
  `params` text CHARACTER SET utf8mb4 NULL COMMENT '操作提交的数据',
  `json_result` text CHARACTER SET utf8mb4 NULL COMMENT '返回数据',
  `del_flag` varchar(3) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '删除标记',
  `ex_info` text CHARACTER SET utf8mb4 NULL COMMENT '异常信息',
  `remarks` varchar(255) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '备注',
  `execute_time` varchar(30) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '服务端处理耗时',
  `msg` varchar(255) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '返回消息',
  `create_time` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `create_user` varchar(50) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '创建人',
  `create_user_id` varchar(36) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '创建人id',
  `update_time` datetime NULL DEFAULT NULL COMMENT '更新时间',
  `update_user` varchar(50) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '更新人',
  `update_user_id` varchar(36) CHARACTER SET utf8mb4 NULL DEFAULT NULL COMMENT '更新人id',
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `tenant_id`(`tenant_id` ASC) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COMMENT = '日志表' ROW_FORMAT = DYNAMIC;
