CREATE TABLE "SYS_THIRD_VERIFY_TICKET_TOKEN"
(
    "ID"          NVARCHAR2(36) PRIMARY KEY,
    "APP_CLIENT"  NVARCHAR2(36),
    "APP_ASK_URI" NVARCHAR2(36),
    "DLZH_DM"     NVARCHAR2(36),
    "SWRY_DM"     NVARCHAR2(36),
    "SWRY_NAME"   NVARCHAR2(100),
    "SWRY_SF_DM"  NVARCHAR2(50),
    "ZSF_BZ"      NVARCHAR2(3),
    "SWJG_DM"     NVARCHAR2(50),
    "SWJG_JC"     NVARCHAR2(3),
    "SJ_SWJG_DM"  NVARCHAR2(50),
    "THEME_CODE"  NVARCHAR2(50),
    "ASK_URI"     NVARCHAR2(200),
    "EXP_TIME"    DATE,
    "CREATE_TIME" DATE
);

COMMENT ON TABLE "SYS_THIRD_VERIFY_TICKET_TOKEN" IS '第三方应用用户校验凭证';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."ID" IS '主键唯一标识';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."DLZH_DM" IS '登录账号';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."APP_CLIENT" IS '应用端标识';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."APP_ASK_URI" IS '应用端访问地址';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."SWRY_DM" IS '税务人员代码';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."SWRY_NAME" IS '税务人员名称';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."SWRY_SF_DM" IS '税务人员身份代码';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."ZSF_BZ" IS '主身份标志';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."SWJG_DM" IS '税务机构代码';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."SWJG_JC" IS '税务机构级次';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."SJ_SWJG_DM" IS '上级税务机构代码';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."THEME_CODE" IS '平台标识';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."ASK_URI" IS '访问地址';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."EXP_TIME" IS '过期时间';
COMMENT ON COLUMN "SYS_THIRD_VERIFY_TICKET_TOKEN"."CREATE_TIME" IS '创建时间';